#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aemebiku <aemebiku@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2014/06/26 15:32:35 by aemebiku          #+#    #+#              #
#    Updated: 2016/01/01 19:53:47 by hbeaujou         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = libftprintf.a

SOURCES =	printf/add_flag.c				\
			printf/add_flag2.c				\
			printf/ft_cut_printf1.c			\
			printf/ft_cut_printf2.c			\
			printf/ft_cut_printf3.c			\
			printf/ft_cut_printf4.c			\
			printf/ft_cut_printf5.c			\
			printf/ft_cut_printf6.c			\
			printf/ft_cut_printf7.c			\
			printf/ft_cut_printf8.c			\
			printf/ft_cut_printf9.c			\
			printf/ft_cut_printf10.c		\
			printf/attrib_conv_erreur.c		\
			printf/attrib_conv_erreur2.c	\
			printf/attrib_conv_c.c			\
			printf/attrib_conv_p.c			\
			printf/attrib_conv_s.c			\
			printf/attrib_conv_s_maj.c		\
			printf/attrib_conv_s2_maj.c		\
			printf/attrib_conv_d_char.c		\
			printf/attrib_conv_d2_char.c	\
			printf/attrib_conv_d_short.c	\
			printf/attrib_conv_d2_short.c	\
			printf/attrib_conv_d_z.c		\
			printf/attrib_conv_d_cc.c		\
			printf/attrib_conv_d2_z.c		\
			printf/attrib_conv_d_j.c		\
			printf/attrib_conv_d2_j.c		\
			printf/attrib_conv_d_ll.c		\
			printf/attrib_conv_d2_ll.c		\
			printf/attrib_conv_d_maj.c		\
			printf/attrib_conv_d2_maj.c		\
			printf/attrib_conv_u_z.c		\
			printf/attrib_conv_u_char.c		\
			printf/attrib_conv_u_short.c	\
			printf/attrib_conv_u_maj.c		\
			printf/attrib_conv_u2_maj.c		\
			printf/attrib_conv_o_j.c		\
			printf/attrib_conv_o_z.c		\
			printf/attrib_conv_o_short.c	\
			printf/attrib_conv_o_char.c		\
			printf/attrib_conv_o_maj.c		\
			printf/attrib_conv_o2_maj.c		\
			printf/attrib_conv_u_llong.c	\
			printf/attrib_conv_u2_llong.c	\
			printf/attrib_conv_u.c			\
			printf/attrib_conv_u2.c			\
			printf/attrib_conv_u_j.c		\
			printf/attrib_conv_c_maj.c		\
			printf/attrib_conv_x_cc.c		\
			printf/attrib_conv_x_char.c		\
			printf/attrib_conv_x_mchr.c		\
			printf/attrib_conv_x_maj.c		\
			printf/attrib_conv_x_long.c		\
			printf/attrib_conv_x2_maj.c		\
			printf/attrib_conv_x_short.c	\
			printf/attrib_conv_x_mshrt.c	\
			printf/attrib_conv_x.c			\
			printf/attrib_conv_x2.c			\
			printf/attrib_conv_o.c			\
			printf/attrib_conv_o2.c			\
			printf/attrib_conv_d.c			\
			printf/attrib_conv_d2.c			\
			printf/attrib_conv.c			\
			printf/attrib_conv_2.c			\
			printf/attrib_conv_3.c			\
			printf/attrib_conv_4.c			\
			printf/attrib_conv_5.c			\
			printf/attrib_conv_6.c			\
			printf/attrib_conv_7.c			\
			printf/attrib_conv_8.c			\
			printf/ft_printf.c				\
			printf/recover_char.c			\
			printf/cut_recover.c			\
			printf/ft_rajout_1.c			\
			printf/ft_rajout_2.c			\
			printf/ft_rajout_3.c			\
			printf/ft_rajout_4.c			\
			printf/ft_rajout_5.c			\
			libft/ft_memset.c				\
			libft/ft_bzero.c				\
			libft/ft_nbrlen.c				\
			libft/ft_memcpy.c				\
			libft/ft_memccpy.c				\
			libft/ft_memmove.c				\
			libft/ft_memchr.c				\
			libft/ft_memcmp.c				\
			libft/ft_strlen.c				\
			libft/ft_strdup.c				\
			libft/ft_strcpy.c				\
			libft/ft_strncpy.c				\
			libft/ft_strcat.c				\
			libft/ft_strncat.c				\
			libft/ft_strlcat.c				\
			libft/ft_strchr.c				\
			libft/ft_strrchr.c				\
			libft/ft_strstr.c				\
			libft/ft_strnstr.c				\
			libft/ft_strcmp.c				\
			libft/ft_strncmp.c				\
			libft/ft_atoi.c					\
			libft/ft_atoi_double.c			\
			libft/ft_atoi_ultra.c			\
			libft/ft_atoi_spec.c			\
			libft/ft_atoi_spec_o.c			\
			libft/ft_atoi_length.c			\
			libft/ft_ulltstr_base.c			\
			libft/ft_isalpha.c				\
			libft/ft_isalnum.c				\
			libft/ft_isascii.c				\
			libft/ft_isdigit.c				\
			libft/ft_isprint.c				\
			libft/ft_toupper.c				\
			libft/ft_tolower.c				\
			libft/ft_memdel.c				\
			libft/ft_strnew.c				\
			libft/ft_strdel.c				\
			libft/ft_strclr.c				\
			libft/ft_striter.c				\
			libft/ft_striteri.c				\
			libft/ft_strequ.c				\
			libft/ft_strnequ.c				\
			libft/ft_strsub.c				\
			libft/ft_strmap.c				\
			libft/ft_strmapi.c				\
			libft/ft_itoa.c					\
			libft/ft_itoa_base.c			\
			libft/ft_ntoa_base.c			\
			libft/ft_itoa_base_maj.c		\
			libft/ft_strsplit.c				\
			libft/ft_strsplit_esc.c			\
			libft/ft_strjoin.c				\
			libft/ft_charjoin.c				\
			libft/ft_strtrim.c				\
			libft/ft_putchar.c				\
			libft/ft_putstr.c				\
			libft/ft_putstr_spec.c			\
			libft/ft_putnbr.c				\


HEADERS	= -I/libft/includes/

OBJECTS	= $(subst .c,.o,$(SOURCES))

WFLAGS	= -g -Wall -Werror -Wextra

CC		= gcc

.SILENT:


$(NAME): $(OBJECTS)
	ar rc $(NAME) $(OBJECTS)
	ranlib $(NAME)
	printf "\e[32m----------------------------------\e[36m\n"
	printf "\e[32m[✔]\e[36m $@"
	printf "\n\e[32m----------------------------------\e[36m"
	printf "\033[0m\n"

all: $(NAME)

%.o: %.c
	$(CC) $(WFLAGS) $(HEADERS) -c -o $@ $^
	printf "\e[32m[✔]\e[36m $@ "
	printf "\033[0m\n"

clean:
	rm -rf $(OBJECTS)
	printf "\e[31m----------------------------------\n"
	printf "[✔]\e[36m $(NAME): Objects deleted\n"
	printf "\e[31m----------------------------------\e[36m"
	printf "\033[0m\n"

fclean: clean
	rm -rf $(NAME)
	printf "\e[31m----------------------------------\n"
	printf "[✔]\e[36m $(NAME): All deleted\n"
	printf "\e[31m----------------------------------\e[36m"
	printf "\033[0m\n"

re: fclean all

.PHONY: re fclean clean all
