NAME =	Colleen Grace Sully
CC =	clang
FLAGS =	-Werror -Wextra -Wall

all:
		$(CC) $(FLAGS) -o Colleen Colleen.c
		$(CC) $(FLAGS) -o Grace Grace.c
		$(CC) $(FLAGS) -o Sully Sully.c

clean:
		@echo "No obj file"

fclean: clean
		-/bin/rm -f $(NAME)

re: fclean all
